package wassel:foundation;

interface postgres {
    resource connection-config {
        constructor(connection-string: string);
    }

    /// A connection to a postgres database
    resource connection {
        /// Open a connection to the database at `address`
        open: static func(config: connection-config) -> result<connection, error>;

        /// Query the database
        query: func(sql: string, params: list<parameter>) -> result<row-set, error>;

        /// Execute statement on the database
        execute: func(sql: string, params: list<parameter>) -> result<u64, error>;
    }

    /// Set of rows
    record row-set {
        columns: list<column>,
        rows: list<row>,
    }

    /// Table column
    record column {
        name: string,
        data-type: data-type,
    }

    /// Query result row
    type row = list<value>;

    /// Postgres data type
    variant data-type {
        binary,
        boolean,
        int32,
        int64,
        text,
        timestamp,
        uuid,

        other(string)
    }

    /// Incoming value
    variant value {
        binary(list<u8>),
        boolean(bool),
        int32(s32),
        int64(s64),
        text(string),
        timestamp(s64),
        uuid(string),

        pg-null,
        unsupported(list<u8>),
    }

    /// Query parameter value
    variant parameter {
        binary(list<u8>),
        boolean(bool),
        int32(s32),
        int64(s64),
        text(string),
        timestamp(s64),
        uuid(string),

        pg-null,
    }

    /// Generic error
    variant error {
        database(database-error),
        query(string),
        other(string),
    }

    /// Postgres error
    record database-error {
        severity: string,
        parsed-severity: option<severity>,
        code: string,
        message: string,
        detail: option<string>,
        hint: option<string>,
        position: option<error-position>,
        where: option<string>,
        schema: option<string>,
        table: option<string>,
        column: option<string>,
        datatype: option<string>,
        constraint: option<string>,
        file: option<string>,
        line: option<u32>,
        routine: option<string>,
    }

    variant severity {
        panic,
        fatal,
        error,
        warning,
        notice,
        debug,
        info,
        log,
    }

    /// Represents the position of an error in a query.
    variant error-position {
        /// A position in the original query.
        original(u32),

        /// A position in an internally generated query.
        internal(error-position-internal),
    }

    record error-position-internal {
        /// The byte position.
        position: u32,
        /// A query generated by the Postgres server.
        query: string,
    }
}
