id = "test-postgres"
name = "Postgres Test"
version = "0.0.0"
component = "${CARGO_TARGET_DIR:target}/wasm32-wasip2/debug/test_postgres.wasm"
endpoint = "/test/postgres/"

[build]
cmd = "cargo build --target wasm32-wasip2"
