[package]
name = "wassel-world"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wassel-interface-http-client.workspace = true
wassel-interface-postgres.workspace = true
wassel-interface-redis.workspace = true

wasmtime-wasi-config.workspace = true
wasmtime-wasi-http.workspace = true
wasmtime-wasi.workspace = true
wasmtime.workspace = true
